server {
  listen 80;

  location /api/ {
    proxy_pass http://backend:8000/api/;
  }

  location /training/ {
    proxy_pass http://training-dashboard:5174/;
  }

  location / {
    proxy_pass http://web:5173/;
  }
}